import nodemailer from 'nodemailer';
import { google } from 'googleapis';
import { EnrichedLead } from '../pipeline/enrich';
import { LeadCategory } from '../pipeline/classify';

const RECIPIENT = process.env.DIGEST_RECIPIENT_EMAIL!;
const FROM = process.env.DIGEST_FROM_EMAIL ?? 'noreply@jaqyi.com';
const SHEET_ID = process.env.GOOGLE_SHEET_ID ?? '';
const USE_SMTP = process.env.USE_SMTP === 'true';

// ─── HTML Builder ─────────────────────────────────────────────────────────────

const CATEGORY_COLORS: Record<LeadCategory, string> = {
  'IT & Software': '#4F46E5',
  'AI & AI Agents': '#7C3AED',
  Automation: '#0891B2',
  'SaaS Products': '#059669',
  'Mobile & Web Apps': '#D97706',
  none: '#6B7280',
};

function scoreEmoji(score: number): string {
  return ['', '🔵', '🟡', '🟠', '🔴', '🔥'][score] ?? '⚪';
}

function renderLeadRow(lead: EnrichedLead): string {
  const color = CATEGORY_COLORS[lead.category] ?? '#6B7280';
  return `
    <tr>
      <td style="padding:10px 8px;border-bottom:1px solid #f0f0f0;">
        <a href="${lead.url}" style="color:${color};font-weight:600;text-decoration:none;">${escapeHtml(lead.title.slice(0, 80))}</a>
        <br/><small style="color:#888;">${lead.source} · ${lead.postedAt.split('T')[0]}</small>
      </td>
      <td style="padding:10px 8px;border-bottom:1px solid #f0f0f0;text-align:center;">
        ${scoreEmoji(lead.buyingIntentScore)} ${lead.buyingIntentScore}/5
      </td>
      <td style="padding:10px 8px;border-bottom:1px solid #f0f0f0;">${escapeHtml(lead.budget ?? '—')}</td>
      <td style="padding:10px 8px;border-bottom:1px solid #f0f0f0;">${escapeHtml(lead.company ?? '—')}</td>
      <td style="padding:10px 8px;border-bottom:1px solid #f0f0f0;">${escapeHtml(lead.email ?? '—')}</td>
    </tr>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildHtml(leads: EnrichedLead[], runDate: string): string {
  const sheetUrl = SHEET_ID
    ? `https://docs.google.com/spreadsheets/d/${SHEET_ID}/edit`
    : '#';

  // Group by category, sort within each group by score desc
  const grouped: Map<LeadCategory, EnrichedLead[]> = new Map();
  for (const lead of leads) {
    if (!grouped.has(lead.category)) grouped.set(lead.category, []);
    grouped.get(lead.category)!.push(lead);
  }
  for (const [, arr] of grouped) {
    arr.sort((a, b) => b.buyingIntentScore - a.buyingIntentScore);
  }

  const sections = [...grouped.entries()]
    .map(([category, catLeads]) => {
      const color = CATEGORY_COLORS[category] ?? '#6B7280';
      const rows = catLeads.map(renderLeadRow).join('');
      return `
        <h2 style="color:${color};font-size:18px;margin:32px 0 8px;">${category} <span style="font-size:13px;color:#999;">(${catLeads.length})</span></h2>
        <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;font-size:14px;">
          <thead>
            <tr style="background:#f8f8f8;color:#555;">
              <th align="left" style="padding:8px;border-bottom:2px solid #e0e0e0;">Listing</th>
              <th style="padding:8px;border-bottom:2px solid #e0e0e0;">Score</th>
              <th align="left" style="padding:8px;border-bottom:2px solid #e0e0e0;">Budget</th>
              <th align="left" style="padding:8px;border-bottom:2px solid #e0e0e0;">Company</th>
              <th align="left" style="padding:8px;border-bottom:2px solid #e0e0e0;">Email</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>`;
    })
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>JAQYI Lead Digest — ${runDate}</title></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#fff;color:#111;max-width:800px;margin:0 auto;padding:24px;">
  <div style="background:linear-gradient(135deg,#4F46E5,#7C3AED);padding:24px 32px;border-radius:12px;color:#fff;margin-bottom:32px;">
    <h1 style="margin:0 0 4px;font-size:24px;">🎯 JAQYI Lead Digest</h1>
    <p style="margin:0;opacity:0.85;">${runDate} · <strong>${leads.length}</strong> new leads ready for outreach</p>
  </div>

  <p style="color:#555;font-size:14px;">
    <a href="${sheetUrl}" style="background:#4F46E5;color:#fff;padding:8px 18px;border-radius:6px;text-decoration:none;font-weight:600;">
      📊 Open Full Tracker →
    </a>
  </p>

  ${sections}

  <hr style="margin:40px 0;border:none;border-top:1px solid #eee;">
  <p style="font-size:12px;color:#aaa;">
    Generated by JAQYI Lead Pipeline · ${new Date().toUTCString()}<br>
    Leads sourced from Freelancer, Upwork, Reddit, Twitter/X, LinkedIn (public).<br>
    Enriched via Apollo.io · Classified by Claude AI.
  </p>
</body></html>`;
}

// ─── Gmail API sender ─────────────────────────────────────────────────────────

async function sendViaGmailApi(subject: string, html: string): Promise<void> {
  const credsRaw = process.env.GMAIL_API_CREDENTIALS_JSON!;
  const creds = JSON.parse(credsRaw);

  const auth = new google.auth.OAuth2(
    creds.client_id,
    creds.client_secret,
    creds.redirect_uri
  );
  auth.setCredentials({
    refresh_token: creds.refresh_token,
  });

  const gmail = google.gmail({ version: 'v1', auth });

  const raw = Buffer.from(
    `To: ${RECIPIENT}\r\nFrom: ${FROM}\r\nSubject: ${subject}\r\nContent-Type: text/html; charset=UTF-8\r\n\r\n${html}`
  )
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');

  await gmail.users.messages.send({
    userId: 'me',
    requestBody: { raw },
  });

  console.log('[digest] Sent via Gmail API');
}

// ─── SMTP fallback sender ─────────────────────────────────────────────────────

async function sendViaSmtp(subject: string, html: string): Promise<void> {
  const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST ?? 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT ?? '587', 10),
    secure: false,
    auth: {
      user: process.env.SMTP_USER!,
      pass: process.env.SMTP_PASS!,
    },
  });

  await transporter.sendMail({
    from: FROM,
    to: RECIPIENT,
    subject,
    html,
  });

  console.log('[digest] Sent via SMTP');
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Builds and sends the daily HTML digest email.
 * Falls back from Gmail API to SMTP if USE_SMTP=true.
 */
export async function sendDigest(leads: EnrichedLead[]): Promise<void> {
  if (leads.length === 0) {
    console.log('[digest] No leads — skipping digest email');
    return;
  }

  const runDate = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const subject = `🎯 JAQYI Leads — ${leads.length} new leads · ${runDate}`;
  const html = buildHtml(leads, runDate);

  if (USE_SMTP) {
    await sendViaSmtp(subject, html);
  } else {
    await sendViaGmailApi(subject, html);
  }
}
